### ISSUE TITLE
function types cannot be generic?

### ISSUE THREAD

**Issue by jesson1** [akutz/go-generics-the-hard-way#14]
I am reading this chapter: https://github.com/akutz/go-generics-the-hard-way/blob/main/03-getting-started/09-multiple-generic-types.md

This chapter mentioned that function types cannot be generic. But why is it designed like this? The reason I can think of is that go language is worried about generic nesting, which affects the compilation speed? Or is there another reason

**Comment by akutz** [comment]
They can be. See the open PR

**Comment by akutz** [comment]
Closed with 6ff67032f6b5d77269a39010b09d6f21f1924f85
